title: Lucien Loiseau
description: Research Engineer — AI · Blockchain · Cryptography · Decentralized Networks
url: https://marlinski.org
logo: /static/avatar.jpeg

github_username: Marlinski
linkedin_username: llucien
twitter_username: lucienloiseau
email: loiseau.lucien@gmail.com
